### ISSUE TITLE
Lower pricing?

### ISSUE THREAD

**Issue by zekiblue** [dokku/dokku-pro-issues#4]
Why there is only one option for pro. We would love monthly payment.

**Comment by josegonzalez** [comment]
There is only one pricing because it simplifies things on my end (subscription billing is a pain). The price is actually quite a bit lower than my final goal, and it's a "lifetime" license so you basically pay once and get all the updates so long as I am releasing them.

My thinking here is that if the price of Dokku Pro is too high, then you're probably not in the demographic of users that actually needs it. Dokku itself remains free and open source, and the cost of Dokku Pro effectively subsidizes my work on Dokku.

At this time, I am not considering any changes to how licensing works.
